spring:
  application:
    name: voucher-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_NAME}
      auto-index-creation: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
server:
  port: 8096
  servlet:
    context-path: /vouchers
services:
  auth-service: ${AUTH_SERVICE_URL:http://localhost:8082/auth}
  user-service: ${USER_SERVICE_URL:http://localhost:8084/users}
  store-service: ${STORE_SERVICE_URL:http://localhost:8088/store}

cache:
  redis_url: ${REDIS_URL}