/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as IndexImport } from './routes/index'
import { Route as NotificationsIndexImport } from './routes/notifications/index'
import { Route as StoreStoreImport } from './routes/store/_store'
import { Route as ProductProductImport } from './routes/product/_product'
import { Route as OrderOrderImport } from './routes/order/_order'
import { Route as PromotionVouchersIndexImport } from './routes/promotion/vouchers/index'
import { Route as StoreStoreDashboardImport } from './routes/store/_store.dashboard'
import { Route as StoreStoreCreateImport } from './routes/store/_store.create'
import { Route as ProductProductManageImport } from './routes/product/_product.manage'
import { Route as ProductProductAddProductImport } from './routes/product/_product.addProduct'
import { Route as OrderOrderManageImport } from './routes/order/_order.manage'
import { Route as PromotionVouchersStoreFollowerIndexImport } from './routes/promotion/vouchers/store-follower/index'
import { Route as PromotionVouchersRegularIndexImport } from './routes/promotion/vouchers/regular/index'
import { Route as PromotionVouchersFreeshipingIndexImport } from './routes/promotion/vouchers/freeshiping/index'
import { Route as PromotionVouchersRegularNewImport } from './routes/promotion/vouchers/regular/new'

// Create Virtual Routes

const StoreImport = createFileRoute('/store')()
const ProductImport = createFileRoute('/product')()
const OrderImport = createFileRoute('/order')()

// Create/Update Routes

const StoreRoute = StoreImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRoute,
} as any)

const ProductRoute = ProductImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRoute,
} as any)

const OrderRoute = OrderImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NotificationsIndexRoute = NotificationsIndexImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRoute,
} as any)

const StoreStoreRoute = StoreStoreImport.update({
  id: '/_store',
  getParentRoute: () => StoreRoute,
} as any)

const ProductProductRoute = ProductProductImport.update({
  id: '/_product',
  getParentRoute: () => ProductRoute,
} as any)

const OrderOrderRoute = OrderOrderImport.update({
  id: '/_order',
  getParentRoute: () => OrderRoute,
} as any)

const PromotionVouchersIndexRoute = PromotionVouchersIndexImport.update({
  id: '/promotion/vouchers/',
  path: '/promotion/vouchers/',
  getParentRoute: () => rootRoute,
} as any)

const StoreStoreDashboardRoute = StoreStoreDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StoreStoreRoute,
} as any)

const StoreStoreCreateRoute = StoreStoreCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => StoreStoreRoute,
} as any)

const ProductProductManageRoute = ProductProductManageImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => ProductProductRoute,
} as any)

const ProductProductAddProductRoute = ProductProductAddProductImport.update({
  id: '/addProduct',
  path: '/addProduct',
  getParentRoute: () => ProductProductRoute,
} as any)

const OrderOrderManageRoute = OrderOrderManageImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => OrderOrderRoute,
} as any)

const PromotionVouchersStoreFollowerIndexRoute =
  PromotionVouchersStoreFollowerIndexImport.update({
    id: '/promotion/vouchers/store-follower/',
    path: '/promotion/vouchers/store-follower/',
    getParentRoute: () => rootRoute,
  } as any)

const PromotionVouchersRegularIndexRoute =
  PromotionVouchersRegularIndexImport.update({
    id: '/promotion/vouchers/regular/',
    path: '/promotion/vouchers/regular/',
    getParentRoute: () => rootRoute,
  } as any)

const PromotionVouchersFreeshipingIndexRoute =
  PromotionVouchersFreeshipingIndexImport.update({
    id: '/promotion/vouchers/freeshiping/',
    path: '/promotion/vouchers/freeshiping/',
    getParentRoute: () => rootRoute,
  } as any)

const PromotionVouchersRegularNewRoute =
  PromotionVouchersRegularNewImport.update({
    id: '/promotion/vouchers/regular/new',
    path: '/promotion/vouchers/regular/new',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderImport
      parentRoute: typeof rootRoute
    }
    '/order/_order': {
      id: '/order/_order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderOrderImport
      parentRoute: typeof OrderRoute
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductImport
      parentRoute: typeof rootRoute
    }
    '/product/_product': {
      id: '/product/_product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductProductImport
      parentRoute: typeof ProductRoute
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreImport
      parentRoute: typeof rootRoute
    }
    '/store/_store': {
      id: '/store/_store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreStoreImport
      parentRoute: typeof StoreRoute
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/order/_order/manage': {
      id: '/order/_order/manage'
      path: '/manage'
      fullPath: '/order/manage'
      preLoaderRoute: typeof OrderOrderManageImport
      parentRoute: typeof OrderOrderImport
    }
    '/product/_product/addProduct': {
      id: '/product/_product/addProduct'
      path: '/addProduct'
      fullPath: '/product/addProduct'
      preLoaderRoute: typeof ProductProductAddProductImport
      parentRoute: typeof ProductProductImport
    }
    '/product/_product/manage': {
      id: '/product/_product/manage'
      path: '/manage'
      fullPath: '/product/manage'
      preLoaderRoute: typeof ProductProductManageImport
      parentRoute: typeof ProductProductImport
    }
    '/store/_store/create': {
      id: '/store/_store/create'
      path: '/create'
      fullPath: '/store/create'
      preLoaderRoute: typeof StoreStoreCreateImport
      parentRoute: typeof StoreStoreImport
    }
    '/store/_store/dashboard': {
      id: '/store/_store/dashboard'
      path: '/dashboard'
      fullPath: '/store/dashboard'
      preLoaderRoute: typeof StoreStoreDashboardImport
      parentRoute: typeof StoreStoreImport
    }
    '/promotion/vouchers/': {
      id: '/promotion/vouchers/'
      path: '/promotion/vouchers'
      fullPath: '/promotion/vouchers'
      preLoaderRoute: typeof PromotionVouchersIndexImport
      parentRoute: typeof rootRoute
    }
    '/promotion/vouchers/regular/new': {
      id: '/promotion/vouchers/regular/new'
      path: '/promotion/vouchers/regular/new'
      fullPath: '/promotion/vouchers/regular/new'
      preLoaderRoute: typeof PromotionVouchersRegularNewImport
      parentRoute: typeof rootRoute
    }
    '/promotion/vouchers/freeshiping/': {
      id: '/promotion/vouchers/freeshiping/'
      path: '/promotion/vouchers/freeshiping'
      fullPath: '/promotion/vouchers/freeshiping'
      preLoaderRoute: typeof PromotionVouchersFreeshipingIndexImport
      parentRoute: typeof rootRoute
    }
    '/promotion/vouchers/regular/': {
      id: '/promotion/vouchers/regular/'
      path: '/promotion/vouchers/regular'
      fullPath: '/promotion/vouchers/regular'
      preLoaderRoute: typeof PromotionVouchersRegularIndexImport
      parentRoute: typeof rootRoute
    }
    '/promotion/vouchers/store-follower/': {
      id: '/promotion/vouchers/store-follower/'
      path: '/promotion/vouchers/store-follower'
      fullPath: '/promotion/vouchers/store-follower'
      preLoaderRoute: typeof PromotionVouchersStoreFollowerIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface OrderOrderRouteChildren {
  OrderOrderManageRoute: typeof OrderOrderManageRoute
}

const OrderOrderRouteChildren: OrderOrderRouteChildren = {
  OrderOrderManageRoute: OrderOrderManageRoute,
}

const OrderOrderRouteWithChildren = OrderOrderRoute._addFileChildren(
  OrderOrderRouteChildren,
)

interface OrderRouteChildren {
  OrderOrderRoute: typeof OrderOrderRouteWithChildren
}

const OrderRouteChildren: OrderRouteChildren = {
  OrderOrderRoute: OrderOrderRouteWithChildren,
}

const OrderRouteWithChildren = OrderRoute._addFileChildren(OrderRouteChildren)

interface ProductProductRouteChildren {
  ProductProductAddProductRoute: typeof ProductProductAddProductRoute
  ProductProductManageRoute: typeof ProductProductManageRoute
}

const ProductProductRouteChildren: ProductProductRouteChildren = {
  ProductProductAddProductRoute: ProductProductAddProductRoute,
  ProductProductManageRoute: ProductProductManageRoute,
}

const ProductProductRouteWithChildren = ProductProductRoute._addFileChildren(
  ProductProductRouteChildren,
)

interface ProductRouteChildren {
  ProductProductRoute: typeof ProductProductRouteWithChildren
}

const ProductRouteChildren: ProductRouteChildren = {
  ProductProductRoute: ProductProductRouteWithChildren,
}

const ProductRouteWithChildren =
  ProductRoute._addFileChildren(ProductRouteChildren)

interface StoreStoreRouteChildren {
  StoreStoreCreateRoute: typeof StoreStoreCreateRoute
  StoreStoreDashboardRoute: typeof StoreStoreDashboardRoute
}

const StoreStoreRouteChildren: StoreStoreRouteChildren = {
  StoreStoreCreateRoute: StoreStoreCreateRoute,
  StoreStoreDashboardRoute: StoreStoreDashboardRoute,
}

const StoreStoreRouteWithChildren = StoreStoreRoute._addFileChildren(
  StoreStoreRouteChildren,
)

interface StoreRouteChildren {
  StoreStoreRoute: typeof StoreStoreRouteWithChildren
}

const StoreRouteChildren: StoreRouteChildren = {
  StoreStoreRoute: StoreStoreRouteWithChildren,
}

const StoreRouteWithChildren = StoreRoute._addFileChildren(StoreRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/order': typeof OrderOrderRouteWithChildren
  '/product': typeof ProductProductRouteWithChildren
  '/store': typeof StoreStoreRouteWithChildren
  '/notifications': typeof NotificationsIndexRoute
  '/order/manage': typeof OrderOrderManageRoute
  '/product/addProduct': typeof ProductProductAddProductRoute
  '/product/manage': typeof ProductProductManageRoute
  '/store/create': typeof StoreStoreCreateRoute
  '/store/dashboard': typeof StoreStoreDashboardRoute
  '/promotion/vouchers': typeof PromotionVouchersIndexRoute
  '/promotion/vouchers/regular/new': typeof PromotionVouchersRegularNewRoute
  '/promotion/vouchers/freeshiping': typeof PromotionVouchersFreeshipingIndexRoute
  '/promotion/vouchers/regular': typeof PromotionVouchersRegularIndexRoute
  '/promotion/vouchers/store-follower': typeof PromotionVouchersStoreFollowerIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/order': typeof OrderOrderRouteWithChildren
  '/product': typeof ProductProductRouteWithChildren
  '/store': typeof StoreStoreRouteWithChildren
  '/notifications': typeof NotificationsIndexRoute
  '/order/manage': typeof OrderOrderManageRoute
  '/product/addProduct': typeof ProductProductAddProductRoute
  '/product/manage': typeof ProductProductManageRoute
  '/store/create': typeof StoreStoreCreateRoute
  '/store/dashboard': typeof StoreStoreDashboardRoute
  '/promotion/vouchers': typeof PromotionVouchersIndexRoute
  '/promotion/vouchers/regular/new': typeof PromotionVouchersRegularNewRoute
  '/promotion/vouchers/freeshiping': typeof PromotionVouchersFreeshipingIndexRoute
  '/promotion/vouchers/regular': typeof PromotionVouchersRegularIndexRoute
  '/promotion/vouchers/store-follower': typeof PromotionVouchersStoreFollowerIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/profile': typeof ProfileRoute
  '/order': typeof OrderRouteWithChildren
  '/order/_order': typeof OrderOrderRouteWithChildren
  '/product': typeof ProductRouteWithChildren
  '/product/_product': typeof ProductProductRouteWithChildren
  '/store': typeof StoreRouteWithChildren
  '/store/_store': typeof StoreStoreRouteWithChildren
  '/notifications/': typeof NotificationsIndexRoute
  '/order/_order/manage': typeof OrderOrderManageRoute
  '/product/_product/addProduct': typeof ProductProductAddProductRoute
  '/product/_product/manage': typeof ProductProductManageRoute
  '/store/_store/create': typeof StoreStoreCreateRoute
  '/store/_store/dashboard': typeof StoreStoreDashboardRoute
  '/promotion/vouchers/': typeof PromotionVouchersIndexRoute
  '/promotion/vouchers/regular/new': typeof PromotionVouchersRegularNewRoute
  '/promotion/vouchers/freeshiping/': typeof PromotionVouchersFreeshipingIndexRoute
  '/promotion/vouchers/regular/': typeof PromotionVouchersRegularIndexRoute
  '/promotion/vouchers/store-follower/': typeof PromotionVouchersStoreFollowerIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/order'
    | '/product'
    | '/store'
    | '/notifications'
    | '/order/manage'
    | '/product/addProduct'
    | '/product/manage'
    | '/store/create'
    | '/store/dashboard'
    | '/promotion/vouchers'
    | '/promotion/vouchers/regular/new'
    | '/promotion/vouchers/freeshiping'
    | '/promotion/vouchers/regular'
    | '/promotion/vouchers/store-follower'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/order'
    | '/product'
    | '/store'
    | '/notifications'
    | '/order/manage'
    | '/product/addProduct'
    | '/product/manage'
    | '/store/create'
    | '/store/dashboard'
    | '/promotion/vouchers'
    | '/promotion/vouchers/regular/new'
    | '/promotion/vouchers/freeshiping'
    | '/promotion/vouchers/regular'
    | '/promotion/vouchers/store-follower'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/order'
    | '/order/_order'
    | '/product'
    | '/product/_product'
    | '/store'
    | '/store/_store'
    | '/notifications/'
    | '/order/_order/manage'
    | '/product/_product/addProduct'
    | '/product/_product/manage'
    | '/store/_store/create'
    | '/store/_store/dashboard'
    | '/promotion/vouchers/'
    | '/promotion/vouchers/regular/new'
    | '/promotion/vouchers/freeshiping/'
    | '/promotion/vouchers/regular/'
    | '/promotion/vouchers/store-follower/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRoute: typeof ProfileRoute
  OrderRoute: typeof OrderRouteWithChildren
  ProductRoute: typeof ProductRouteWithChildren
  StoreRoute: typeof StoreRouteWithChildren
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  PromotionVouchersIndexRoute: typeof PromotionVouchersIndexRoute
  PromotionVouchersRegularNewRoute: typeof PromotionVouchersRegularNewRoute
  PromotionVouchersFreeshipingIndexRoute: typeof PromotionVouchersFreeshipingIndexRoute
  PromotionVouchersRegularIndexRoute: typeof PromotionVouchersRegularIndexRoute
  PromotionVouchersStoreFollowerIndexRoute: typeof PromotionVouchersStoreFollowerIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRoute: ProfileRoute,
  OrderRoute: OrderRouteWithChildren,
  ProductRoute: ProductRouteWithChildren,
  StoreRoute: StoreRouteWithChildren,
  NotificationsIndexRoute: NotificationsIndexRoute,
  PromotionVouchersIndexRoute: PromotionVouchersIndexRoute,
  PromotionVouchersRegularNewRoute: PromotionVouchersRegularNewRoute,
  PromotionVouchersFreeshipingIndexRoute:
    PromotionVouchersFreeshipingIndexRoute,
  PromotionVouchersRegularIndexRoute: PromotionVouchersRegularIndexRoute,
  PromotionVouchersStoreFollowerIndexRoute:
    PromotionVouchersStoreFollowerIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/profile",
        "/order",
        "/product",
        "/store",
        "/notifications/",
        "/promotion/vouchers/",
        "/promotion/vouchers/regular/new",
        "/promotion/vouchers/freeshiping/",
        "/promotion/vouchers/regular/",
        "/promotion/vouchers/store-follower/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/order": {
      "filePath": "order",
      "children": [
        "/order/_order"
      ]
    },
    "/order/_order": {
      "filePath": "order/_order.tsx",
      "parent": "/order",
      "children": [
        "/order/_order/manage"
      ]
    },
    "/product": {
      "filePath": "product",
      "children": [
        "/product/_product"
      ]
    },
    "/product/_product": {
      "filePath": "product/_product.tsx",
      "parent": "/product",
      "children": [
        "/product/_product/addProduct",
        "/product/_product/manage"
      ]
    },
    "/store": {
      "filePath": "store",
      "children": [
        "/store/_store"
      ]
    },
    "/store/_store": {
      "filePath": "store/_store.tsx",
      "parent": "/store",
      "children": [
        "/store/_store/create",
        "/store/_store/dashboard"
      ]
    },
    "/notifications/": {
      "filePath": "notifications/index.tsx"
    },
    "/order/_order/manage": {
      "filePath": "order/_order.manage.tsx",
      "parent": "/order/_order"
    },
    "/product/_product/addProduct": {
      "filePath": "product/_product.addProduct.tsx",
      "parent": "/product/_product"
    },
    "/product/_product/manage": {
      "filePath": "product/_product.manage.tsx",
      "parent": "/product/_product"
    },
    "/store/_store/create": {
      "filePath": "store/_store.create.tsx",
      "parent": "/store/_store"
    },
    "/store/_store/dashboard": {
      "filePath": "store/_store.dashboard.tsx",
      "parent": "/store/_store"
    },
    "/promotion/vouchers/": {
      "filePath": "promotion/vouchers/index.tsx"
    },
    "/promotion/vouchers/regular/new": {
      "filePath": "promotion/vouchers/regular/new.tsx"
    },
    "/promotion/vouchers/freeshiping/": {
      "filePath": "promotion/vouchers/freeshiping/index.tsx"
    },
    "/promotion/vouchers/regular/": {
      "filePath": "promotion/vouchers/regular/index.tsx"
    },
    "/promotion/vouchers/store-follower/": {
      "filePath": "promotion/vouchers/store-follower/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
