spring:
  application:
    name: socket-service
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
server:
  port: 4008
services:
  auth-service: ${AUTH_SERVICE_URL:http://localhost:8082/auth}
  user-service: ${USER_SERVICE_URL:http://localhost:8082/users}



cache:
  redis_url: ${REDIS_URL}
logging:
  level:
    org.springframework.web.socket: debug
    org.springframework.messaging: debug
    org:
      springframework:
        security: debug

