version: '3.9'
services:
  kafka:
    image: bitnami/kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_AUTHORIZER_CLASS_NAME=  # Để trống hoặc bỏ hoàn toàn
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true  # Giúp Kafka không yêu cầu ACL nếu không có cấu hình
    ports:
      - "9092:9092"

  akhq:
    image: tchiotludo/akhq:latest
    ports:
      - "8080:8080"
    environment:
      AKHQ_CONFIGURATION: |
        micronaut:
          security:
            enabled: false  # Tắt bảo mật trong AKHQ
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "kafka:9092"  # Đảm bảo đúng địa chỉ Kafka
    depends_on:
      - kafka
