version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"  # REST API port
      - "6334:6334"  # gRPC API port
    environment:
      - QDRANT__SERVICE__HOST=0.0.0.0
    restart: unless-stopped
    mem_limit: 500m       # Giới hạn RAM
    mem_reservation: 256m # Đặt trước RAM tối thiểu (tùy chọn)
    cpus: "1"             # Giới hạn CPU


