spring:
  application:
    name: media-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_NAME}
      auto-index-creation: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  servlet:
    multipart:
      max-request-size: 510MB
      enabled: true
      max-file-size: 500MB
server:
  port: 8096
  servlet:
    context-path: /media
services:
  auth-service: ${AUTH_SERVICE_URL:http://localhost:8082/auth}
  user-service: ${USER_SERVICE_URL:http://localhost:8084/users}
  store-service: ${STORE_SERVICE_URL:http://localhost:8088/store}
cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  dir-prefix: "lemoo/"
  secure-url-expire-in: 2 # 2 hour

assets:

cache:
  redis_url: ${REDIS_URL}