version: "3.8"

services:
    api-gateway:
        image: zeustakeshi/lemoo-gateway
        ports:
            - "80:8080"
        env_file:
            - ./env/gateway.env
        networks:
            - lemoo_network

    auth-service:
        image: zeustakeshi/lemoo-auth-service
        ports:
            - "8082:8082"
        env_file:
            - ./env/auth-service.env
        volumes:
            - ./keys:/app/keys
        networks:
            - lemoo_network

    user-service:
        image: zeustakeshi/lemoo-user-service
        ports:
            - "8084:8084"
        env_file:
            - ./env/user-service.env
        networks:
            - lemoo_network

    store-service:
        image: zeustakeshi/lemoo-store-service
        ports:
            - "8088:8088"
        env_file:
            - ./env/store-service.env
        networks:
            - lemoo_network

    product-service:
        image: zeustakeshi/lemoo-product-service
        ports:
            - "8090:8090"
        env_file:
            - ./env/product-service.env
        networks:
            - lemoo_network

    video-service:
        image: zeustakeshi/lemoo-video-service
        ports:
            - "8092:8092"
        env_file:
            - ./env/video-service.env
        networks:
            - lemoo_network

    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        deploy:
            resources:
                reservations:
                    memory: "200M" # Đặt bộ nhớ tối thiểu là 200 MB
                limits:
                    memory: "1G" # Đặt bộ nhớ tối đa là 1 GB
        networks:
            - lemoo_network
        depends_on:
            - zookeeper

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        networks:
            - lemoo_network

networks:
    lemoo_network:
        driver: overlay
