version: '3.9'

services:
  #  kong-database:
  #    image: postgres:14
  #    environment:
  #      POSTGRES_USER: kong
  #      POSTGRES_PASSWORD: kong
  #      POSTGRES_DB: kong
  #    volumes:
  #      - kong-db-data:/var/lib/postgresql/data
  #    networks:
  #      - kong-net

  kong-migrations:
    image: kong:3
    command: kong migrations bootstrap
    env_file:
      - ../env/env/gateway.env
    networks:
      - kong-net
    deploy:
      replicas: 1

  kong:
    image: kong:3
    env_file:
      - ../env/env/gateway.env
    environment:
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    networks:
      - kong-net
      - lemoo-net
    ports:
      - "80:8000" # Proxy port (client-facing API)
      - "8001:8001" # Admin API port (internal)
    deploy:
      replicas: 1

  konga:
    image: pantsel/konga
    env_file:
      - ../env/env/gateway.env
    environment:
      KONGA_PROXY_HOST: kong:8001
      KONGA_PORT: 1337
    ports:
      - "1337:1337"  # Port to access Konga's UI
    networks:
      - kong-net
    depends_on:
      - kong

networks:
  kong-net:
    driver: overlay
  lemoo-net:
    external: true

volumes:
  kong-db-data: