version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000" # Default port to access Portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Link Docker socket to allow Portainer to interact with Docker daemon
      - portainer_data:/data # Volume to store Portainer data
    deploy:
      mode: replicated
      replicas: 1 # Run only one instance of Portainer
      placement:
        constraints:
          - node.role == manager # Run Portainer on the Master (manager) node
    networks:
      - portainer_network

  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Link Docker socket
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global # Agent will run on all nodes
    networks:
      - portainer_network

volumes:
  portainer_data: # Volume to store Portainer data

networks:
  portainer_network:
    driver: overlay # Use overlay network for Docker Swarm
