spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:127.0.0.1:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:127.0.0.1:9092}
      group-id: user_group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: '*'
server:
  port: 8082
jwt:
  key:
    access-token:
      public-key: ${ACCESS_TOKEN_PUBLIC_KEY_PATH:../../keys/accessToken/publicKey.pem}
      private-key: ${ACCESS_TOKEN_PRIVATE_KEY_PATH:../../keys/accessToken/privateKey.pem}
      expireIn: 2 # hour
    refresh-token:
      public-key: ${REFRESH_TOKEN_PUBLIC_KEY_PATH:../../keys/refreshToken/publicKey.pem}
      private-key: ${REFRESH_TOKEN_PRIVATE_KEY_PATH:../../keys/refreshToken/privateKey.pem}
      expireIn: 120 # hour == 5 days
cache:
  redis_url: ${REDIS_URL}
assets:
  default-avatar-man: ${USER_DEFAULT_AVATAR_MAN:https://res.cloudinary.com/dvo9krira/image/upload/v1729261457/Lemoo/user/avatar/default-avatar-man.jpg}

