/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContactsIndexImport } from './routes/contacts/index'
import { Route as SettingsGeneralImport } from './routes/settings/general'
import { Route as ContactsSentImport } from './routes/contacts/sent'
import { Route as ContactsRequestImport } from './routes/contacts/request'
import { Route as chatschatImport } from './routes/(chats)/__chat'
import { Route as chatschatIndexImport } from './routes/(chats)/__chat.index'

// Create Virtual Routes

const chatsImport = createFileRoute('/(chats)')()

// Create/Update Routes

const chatsRoute = chatsImport.update({
  id: '/(chats)',
  getParentRoute: () => rootRoute,
} as any)

const ContactsIndexRoute = ContactsIndexImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsGeneralRoute = SettingsGeneralImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => rootRoute,
} as any)

const ContactsSentRoute = ContactsSentImport.update({
  id: '/contacts/sent',
  path: '/contacts/sent',
  getParentRoute: () => rootRoute,
} as any)

const ContactsRequestRoute = ContactsRequestImport.update({
  id: '/contacts/request',
  path: '/contacts/request',
  getParentRoute: () => rootRoute,
} as any)

const chatschatRoute = chatschatImport.update({
  id: '/__chat',
  getParentRoute: () => chatsRoute,
} as any)

const chatschatIndexRoute = chatschatIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => chatschatRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(chats)': {
      id: '/(chats)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof chatsImport
      parentRoute: typeof rootRoute
    }
    '/(chats)/__chat': {
      id: '/(chats)/__chat'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof chatschatImport
      parentRoute: typeof chatsRoute
    }
    '/contacts/request': {
      id: '/contacts/request'
      path: '/contacts/request'
      fullPath: '/contacts/request'
      preLoaderRoute: typeof ContactsRequestImport
      parentRoute: typeof rootRoute
    }
    '/contacts/sent': {
      id: '/contacts/sent'
      path: '/contacts/sent'
      fullPath: '/contacts/sent'
      preLoaderRoute: typeof ContactsSentImport
      parentRoute: typeof rootRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralImport
      parentRoute: typeof rootRoute
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsIndexImport
      parentRoute: typeof rootRoute
    }
    '/(chats)/__chat/': {
      id: '/(chats)/__chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof chatschatIndexImport
      parentRoute: typeof chatschatImport
    }
  }
}

// Create and export the route tree

interface chatschatRouteChildren {
  chatschatIndexRoute: typeof chatschatIndexRoute
}

const chatschatRouteChildren: chatschatRouteChildren = {
  chatschatIndexRoute: chatschatIndexRoute,
}

const chatschatRouteWithChildren = chatschatRoute._addFileChildren(
  chatschatRouteChildren,
)

interface chatsRouteChildren {
  chatschatRoute: typeof chatschatRouteWithChildren
}

const chatsRouteChildren: chatsRouteChildren = {
  chatschatRoute: chatschatRouteWithChildren,
}

const chatsRouteWithChildren = chatsRoute._addFileChildren(chatsRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof chatschatIndexRoute
  '/contacts/request': typeof ContactsRequestRoute
  '/contacts/sent': typeof ContactsSentRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/contacts': typeof ContactsIndexRoute
}

export interface FileRoutesByTo {
  '/contacts/request': typeof ContactsRequestRoute
  '/contacts/sent': typeof ContactsSentRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/contacts': typeof ContactsIndexRoute
  '/': typeof chatschatIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/(chats)': typeof chatsRouteWithChildren
  '/(chats)/__chat': typeof chatschatRouteWithChildren
  '/contacts/request': typeof ContactsRequestRoute
  '/contacts/sent': typeof ContactsSentRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/contacts/': typeof ContactsIndexRoute
  '/(chats)/__chat/': typeof chatschatIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts/request'
    | '/contacts/sent'
    | '/settings/general'
    | '/contacts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contacts/request'
    | '/contacts/sent'
    | '/settings/general'
    | '/contacts'
    | '/'
  id:
    | '__root__'
    | '/(chats)'
    | '/(chats)/__chat'
    | '/contacts/request'
    | '/contacts/sent'
    | '/settings/general'
    | '/contacts/'
    | '/(chats)/__chat/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  chatsRoute: typeof chatsRouteWithChildren
  ContactsRequestRoute: typeof ContactsRequestRoute
  ContactsSentRoute: typeof ContactsSentRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  chatsRoute: chatsRouteWithChildren,
  ContactsRequestRoute: ContactsRequestRoute,
  ContactsSentRoute: ContactsSentRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  ContactsIndexRoute: ContactsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/(chats)",
        "/contacts/request",
        "/contacts/sent",
        "/settings/general",
        "/contacts/"
      ]
    },
    "/(chats)": {
      "filePath": "(chats)",
      "children": [
        "/(chats)/__chat"
      ]
    },
    "/(chats)/__chat": {
      "filePath": "(chats)/__chat.tsx",
      "parent": "/(chats)",
      "children": [
        "/(chats)/__chat/"
      ]
    },
    "/contacts/request": {
      "filePath": "contacts/request.tsx"
    },
    "/contacts/sent": {
      "filePath": "contacts/sent.tsx"
    },
    "/settings/general": {
      "filePath": "settings/general.tsx"
    },
    "/contacts/": {
      "filePath": "contacts/index.tsx"
    },
    "/(chats)/__chat/": {
      "filePath": "(chats)/__chat.index.tsx",
      "parent": "/(chats)/__chat"
    }
  }
}
ROUTE_MANIFEST_END */
