name: auth_service_deployment
on:
  push:
    branches:
      - test/deployment
    paths:
      - 'api/Auth/**'
      - '.github/workflows/ci_auth_service_deployment.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_URL: "jdbc:postgresql://roundhouse.proxy.rlwy.net:10569/railway" # test
      DB_USER: "postgres" # test
      DB_PASSWORD: "BvhZgytXgNAKiEHwyvfAOkyoKUpBhMCa" # test
      REDIS_URL: "redis://default:nMKNongMYfuZzdFqVclBBnHQNQhhHAtd@junction.proxy.rlwy.net:52125" # test
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Setup token key
        working-directory: ./keys
        run: bash key_generator.sh
      - name: Build with Maven
        working-directory: ./api/Auth
        run: mvn clean package
      - name: Build the Docker image
        working-directory: ./api/Auth
        run: docker build . --file Dockerfile --tag zeustakeshi/lemoo-auth-service:latest
      - name: login Dockerhub
        run: |
          docker login -u "zeustakeshi" -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push zeustakeshi/lemoo-auth-service:latest
          
          
          
          
