name: chat_ai_mcp_server_deployment
on:
  pull_request:
    branches:
      - main
    paths:
      - 'api/Chat_ai_mcp_server/**'
      - '.github/workflows/ci_chat_ai_mcp_server_deployment.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ./api/Chat_ai_mcp_server
        run: mvn clean package
      - name: Build the Docker image
        working-directory: ./api/Chat_ai_mcp_server
        run: docker build . --file Dockerfile --tag zeustakeshi/lemoo-chat-ai-mcp-server:latest
      - name: login Dockerhub
        run: |
          docker login -u "zeustakeshi" -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push zeustakeshi/lemoo-chat-ai-mcp-server:latest
          
          
          
          
