name: gateway_build_check
on:
  pull_request:
    branches:
      - dev
    paths:
      - 'api/Gateway/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AUTH_SERVICE_URL: ${{ secrets.AUTH_SERVICE_URL }}
      USER_SERVICE_URL: ${{ secrets.USER_SERVICE_URL }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ./api/Gateway
        run: mvn clean package

          
          
