name: gateway_deployment
on:
  push:
    branches:
      - dev
      - test
    paths:
      - 'api/Gateway/**'
      - '.github/workflows/ci_gateway_deployment.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ./api/Gateway
        run: mvn clean package
      - name: Build the Docker image
        working-directory: ./api/Gateway
        run: docker build . --file Dockerfile --tag zeustakeshi/lemoo-gateway:latest
      - name: login Dockerhub
        run: |
          docker login -u "zeustakeshi" -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push zeustakeshi/lemoo-gateway:latest
          
          
          
          
