name: promotion_service_deployment
on:
  push:
    branches:
      - test/deployment
    paths:
      - 'api/Promotion/**'
      - '.github/workflows/ci_promotion_service_deployment.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: "mongodb://mongo:MRkQigmGAwIthFcCEDCRzwnkXlnXvoML@autorack.proxy.rlwy.net:58208"
      MONGODB_NAME: "test"
      CLOUDINARY_NAME: ${{secrets.CLOUDINARY_NAME}}
      CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
      CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ./api/Promotion
        run: mvn clean package
      - name: Build the Docker image
        working-directory: ./api/Promotion
        run: docker build . --file Dockerfile --tag zeustakeshi/lemoo-promotion-service:latest
      - name: login Dockerhub
        run: |
          docker login -u "zeustakeshi" -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push zeustakeshi/lemoo-promotion-service:latest
          
          
          
          
