name: socket_service_deployment
on:
  push:
    branches:
      - test/deployment
    paths:
      - 'api/Socket/**'
      - '.github/workflows/ci_socket_service_deployment.yml'
  pull_request:
    branches:
      - test/deployment
    paths:
      - 'api/Socket/**'
      - '.github/workflows/ci_socket_service_deployment.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USER_SERVICE_URL: "http://user-service"
      AUTH_SERVICE_URL: "http://auth-service"
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ./api/Socket
        run: mvn clean package
      - name: Build the Docker image
        working-directory: ./api/Socket
        run: docker build . --file Dockerfile --tag zeustakeshi/lemoo-socket-service:latest
      - name: login Dockerhub
        run: |
          docker login -u "zeustakeshi" -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push zeustakeshi/lemoo-socket-service:latest
          
          
          
          
