name: user_service_build_check
on:
  pull_request:
    branches:
      - dev
    paths:
      - 'api/User/**'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.USER_DATABASE_URL }}
      DB_USER: ${{ secrets.USER_DB_USER }}
      DB_PASSWORD: ${{ secrets.USER_DB_PASSWORD }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ./api/User
        run: mvn clean package
