name: user_service_deployment
on:
  push:
    branches:
      - test/deployment
    paths:
      - 'api/User/**'
      - '.github/workflows/ci_user_service_deployment.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_URL: "jdbc:postgresql://junction.proxy.rlwy.net:41025/railway"
      DB_USER: "postgres"
      DB_PASSWORD: "EoYnDHaHzfqLFzTfDlvRgwhTrxFGbRIr"
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ./api/User
        run: mvn clean package
      - name: Build the Docker image
        working-directory: ./api/User
        run: docker build . --file Dockerfile --tag zeustakeshi/lemoo-user-service:latest
      - name: login Dockerhub
        run: |
          docker login -u "zeustakeshi" -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push zeustakeshi/lemoo-user-service:latest
          
          
          
          
