name: video_service_deployment
on:
  push:
    branches:
      - dev
      - test
    paths:
      - 'api/Video/**'
      - '.github/workflows/ci_video_service_deployment.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI: ${{ secrets.VIDEO_MONGODB_URI }}
      MONGODB_NAME: ${{secrets.VIDEO_MONGODB_NAME}}
      CLOUDINARY_NAME: ${{secrets.CLOUDINARY_NAME}}
      CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
      CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        working-directory: ./api/Video
        run: mvn clean package
      - name: Build the Docker image
        working-directory: ./api/Video
        run: docker build . --file Dockerfile --tag zeustakeshi/lemoo-video-service:latest
      - name: login Dockerhub
        run: |
          docker login -u "zeustakeshi" -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push zeustakeshi/lemoo-video-service:latest
          
          
          
          
